### ISSUE TITLE
Use cookstyle instead of rubocop if available

### ISSUE THREAD

**Issue by smith** [pendrica/vscode-chef#12]
Newer versions of Chef DK include [Cookstyle](https://github.com/chef/cookstyle), which is a specific version of Rubocop with specific rules for Chef cookbooks.

By default, instead of using rubocop, this extension should look for cookstyle and use that if possible.

**Comment by stuartpreston** [comment]
Yes, I think it's time. Do we still agree with the default of leaving it disabled but enabled via workspace or user setting?

**Comment by smith** [comment]
I think rubocop is enabled by default (from my tests and from https://github.com/pendrica/vscode-chef#rubocop-linting), but foodcritic is disabled by default. I'd prefer leaving it enabled by default with cookstyle as well, but don't feel strongly about it since I could just turn it on if needed.
