### ISSUE TITLE
Add support for a cookstyle config file

### ISSUE THREAD

**Issue by rdean716** [pendrica/vscode-chef#14]
Really enjoy the extension - thank you!

It would be nice to be able to configure a per workspace configuration file.  For example, we regularly set the Style/EndofLine cop to  enabled: false via a configuration file.  Not sure how difficult that would be to implement, but it would keep the user experience consistent how we manage the behaviors of various cops in our projects.

Thanks for considering this.

**Comment by stuartpreston** [comment]
This sounds like a reasonable request!  If we exposed a workspace setting like `rubocop.configfile` to enable this and you were able to set the value to either a relative path within the workspace or an explicit path that could be outside the workspace, would that work for you?  This would be the equivalent of calling ```cookstyle --config #{rubocop.configfile}``` from your command line.

**Comment by rdean716** [comment]
I think that would work well for the scenario I described. 

I looked at the code earlier today and I'm not sure I understand it completely, but I may attempt to address this myself in the next few days.

**Comment by stuartpreston** [comment]
I had a look tonight and as I haven't touched the code for a while had to upgrade a lot of the underlying framework (latest Typescript, linting tools, typings etc...) - anyway this is now fixed as of extension 0.6.3 - please give it a go and report back!

**Comment by rdean716** [comment]
This appears to not work as expected - with version 0.6.3 i've defined my config file as follows:
`"rubocop.configFile": ".rubocop_todo.yml"`

It contains:
`Style/EndOfLine:
  Enabled: false`

Code is still alerting me to this issue.  But, if I run cookstyle manually it runs without flagging this issue in my file:

` cookstyle --config .\.rubocop_todo.yml .
Inspecting 8 files
........

8 files inspected, no offenses detected`

Thoughts?

**Comment by rdean716** [comment]
ahh... need to reload code after making my workspace settings... thanks so much!

**Comment by stuartpreston** [comment]
Great.  A reload is required for this config change if the project has already been loaded (as the extension only loads this config at load time).  Closing this one now.
