### ISSUE TITLE
Don't see foodcrtic output

### ISSUE THREAD

**Issue by donwlewis** [pendrica/vscode-chef#16]
I am not sure if I am doing something wrong but I am not seeing any output from foodcritic.  I would assume I would see it in the problems area, but I don't see anything there.

**Comment by stuartpreston** [comment]
The problems area is where you should see the output.  Are you opening the root of a Chef repo, the folder structure is fairly important.  Also did you enable the Foodcritic plugin (it's disabled by default): https://github.com/pendrica/vscode-chef/blob/master/README.md#foodcritic-analysis-experimental

**Comment by donwlewis** [comment]
So that is where I might be having the issue.  I am not leveraging a chef repo, but opening the individual cookbooks as separate projects.  Yes I do have foodcritic enabled.

**Comment by stuartpreston** [comment]
It should support opening a cookbook individually.  There may well be an issue with reporting the data back.  If you go to Help > Toggle Developer Tools and open a file within the workspace you should see some debug output.  

I just tested on my system and got a failure in a test cookbook - this may be something that needs further investigation to get it to work successfully.

![image](https://user-images.githubusercontent.com/6384654/32962622-0c3de09c-cbc5-11e7-8cf3-dad9911034ac.png)

**Comment by donwlewis** [comment]
So I see foodcritic output from the developer console with no errors, but still not seeing anything in the actual problems section:

![image](https://user-images.githubusercontent.com/16139164/32963664-8f12b802-cb85-11e7-8848-ca799ca9dba4.png)

**Comment by stuartpreston** [comment]
Looks like a bug I'm afraid to say at this point.  Probably to do with the exit code of 3 being seen from Foodcritic.  We will have to investigate further.

**Comment by stuartpreston** [comment]
Please could you retry this in the latest version (0.6.4) and reopen if there continues to be an issue.  Thanks!

**Comment by donwlewis** [comment]
Everything works now!  Thanks!  FYI Changelog has the wrong date (2016 instead of 2017).
