### ISSUE TITLE
FoodCritic Output Not Updating on Save

### ISSUE THREAD

**Issue by SeanSith** [pendrica/vscode-chef#19]
When adding exclusions to `.foodcritic` in cookbook root or fixing violations (e.g. adding `issues_url` to `metadata.rb`), the 'Problems' tab doesn't update. Closing and reopening VS Code and saving does allow the next run to update the 'Problems' tab, but a subsequent set of changes (introducing violations) does not update the tab. It seems that if the tab is already populated with errors, it will not update it.

macOS 10.13.4
VS Code 1.21.1
vscode-chef 0.6.4
Chef Development Kit Version: 2.5.3
chef-client version: 13.8.5
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.20.0
inspec version: 1.51.21

![image](https://user-images.githubusercontent.com/5067650/38329476-ec753bc0-381b-11e8-9820-cd3e23ea8ee6.png)

**Comment by SeanSith** [comment]
To flesh out the rest of my environment based on previous GH issues: 

- I enabled foodcritic support in the workspace instead of in user settings
- My top level directory is the result of a `chef generate cookbook`
- Foodcritic is available at `/opt/chefdk/bin/foodcritic`

I also installed Rubocop in my normal, non-ChefDK Ruby and that didn't seem to change the situation.

**Comment by stuartpreston** [comment]
Thanks for reporting, I’m AFK for a few days but will look into this ASAP.  As you can see from the code, there’s some logging to the console in Developer Mode - is that of any use?

**Comment by SeanSith** [comment]
No worries! I hope I made a reasonable attempt to fix the issue based on my guess. I've tested it locally myself (and it works), but as I'm not well versed in JavaScript, I'm making a wild guess as to whether or not that #20 is a good way to fix it.

Thanks for this extension! It's helped me immensely.

**Comment by stuartpreston** [comment]
Released in 0.7.0 - we'll continue to look for small improvements to this - thanks
