### ISSUE TITLE
Should be updated to work with chef-workstation

### ISSUE THREAD

**Issue by kmf** [pendrica/vscode-chef#27]
or at least the docs should reflect how it make it work with ```chef-workstation```

**Comment by stuartpreston** [comment]
@kmf What would you like to see work differently when using the extension with Chef Workstation?

**Comment by kmf** [comment]
I'm trying to see if ```foodcritic``` works with the plugin ... or would I need to update various paths?

**Comment by kmf** [comment]
thanks.
