### ISSUE TITLE
Adding extension stops auto-closing quotes

### ISSUE THREAD

**Issue by scryb3** [pendrica/vscode-chef#6]
I'm getting autoclosing brackets and braces but single and double quotes no longer auto-close when typed

**Comment by stuartpreston** [comment]
Hi! Has this ever worked for you?  I also see the same when working on a Ruby file without the Chef extension is uninstalled.  Would you mind raising this issue at the VSCode. https://github.com/microsoft/vscode/issues

**Comment by scryb3** [comment]
Oh dear, I think I had editor confusion going. Atom was working, VScode does not with (or without) the extension. Sorry for the false alarm, and yes, I will submit it to the right repo. Thanks again for an awesome extension!

**Comment by stuartpreston** [comment]
@scryb3 By accident I spotted that this issue seems to have been fixed in VS Code 1.1.0 :)

**Comment by scryb3** [comment]
Sorry, I forgot to link you to the issue I opened on the VSCode repo. Someone had the code fixed the same day, nice to see it made release quickly too!
