### ISSUE TITLE
Run kitchen from visual studio code

### ISSUE THREAD

**Issue by mhedgpeth** [pendrica/vscode-chef#8]
I would love to press Ctrl+P then Kitchen: Converge, Test, Verify. It would be even greater if I had multiple cookbooks open, it would give me a list (starting with the one closest to my current file) that I could run it on.

**Comment by stuartpreston** [comment]
I don't think there's a decent way to pop a UI for the 2nd request. But I think the first is do-able. What about the destroy step? Would kitchen test be enough for an increment?

**Comment by mhedgpeth** [comment]
Yeah I was thinking how when you do > ext install it will show you a dropdown there. It also does that for the git functionality (git checkout ).

Yeah kitchen test would be a great start. If you did one, would it be difficult to do them all?

**Comment by stuartpreston** [comment]
I'll check it out. Absolutely I'd add Converge, Verify and Test and unique options. Just want to make sure it's clean what each one doe so I don't get the blame for long running compute resource :-)

**Comment by mhedgpeth** [comment]
Good point, :) I'm looking forward to it. Thanks again for the great plugin, I'm really starting to enjoy code as I get more into it.

**Comment by mhedgpeth** [comment]
It looks like my colleague Jirka (@jirkafajfr) beat us to it: https://marketplace.visualstudio.com/items?itemName=jirkafajfr.vscode-kitchen

He's the one who got me more into VS Code. :)

**Comment by stuartpreston** [comment]
Oh that's messy.
Just about sums things up at the moment!
